services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    restart: always
    ports:
      - 18000:3000

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 3000
    restart: always
    depends_on:
      - database
    ports:
      - 18001:3000

  database:
    container_name: database
    image: mysql:8.0-debian
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 18306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

